---
- name: Jenkins install
  become: yes
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    published_ports: 8080:8080
    container_default_behavior: no_defaults
    volumes:
      - jenkins-docker-cert:/cert/client
      - jenkins-data:/var/jenkins_home